
;;; All the macros and the scheme-object printing procedure
;;; are defined in compiler.s
%include "compiler.s"

section .bss
;;; This pointer is used to manage allocations on our heap.
malloc_pointer:
    resq 1

section .data
const_tbl:
MAKE_VOID
MAKE_NIL
MAKE_BOOL(0)
MAKE_BOOL(1)
MAKE_LITERAL_INT(1)

;;; These macro definitions are required for the primitive
;;; definitions in the epilogue to work properly
%define SOB_VOID_ADDRESS const_tbl+0
%define SOB_NIL_ADDRESS const_tbl+1
%define SOB_FALSE_ADDRESS const_tbl+2
%define SOB_TRUE_ADDRESS const_tbl+4

fvar_tbl:
dq T_UNDEFINED
dq T_UNDEFINED
dq T_UNDEFINED
dq T_UNDEFINED
dq T_UNDEFINED
dq T_UNDEFINED
dq T_UNDEFINED
dq T_UNDEFINED
dq T_UNDEFINED
dq T_UNDEFINED
dq T_UNDEFINED
dq T_UNDEFINED
dq T_UNDEFINED
dq T_UNDEFINED
dq T_UNDEFINED
dq T_UNDEFINED
dq T_UNDEFINED
dq T_UNDEFINED
dq T_UNDEFINED
dq T_UNDEFINED
dq T_UNDEFINED
dq T_UNDEFINED
dq T_UNDEFINED
dq T_UNDEFINED
dq T_UNDEFINED
dq T_UNDEFINED
dq T_UNDEFINED
dq T_UNDEFINED
dq T_UNDEFINED
dq T_UNDEFINED

global main
section .text
main:
    push rbp

    ;; set up the heap
    mov rdi, GB(4)
    call malloc
    mov [malloc_pointer], rax

    ;; Set up the dummy activation frame
    ;; The dummy return address is T_UNDEFINED
    ;; (which a is a macro for 0) so that returning
    ;; from the top level (which SHOULD NOT HAPPEN
    ;; AND IS A BUG) will cause a segfault.
    push 0
    push qword SOB_NIL_ADDRESS
    push qword T_UNDEFINED
    push rsp
    mov rbp,rsp

    ;; Set up the primitive stdlib fvars:
    ;; Since the primtive procedures are defined in assembly,
    ;; they are not generated by scheme (define ...) expressions.
    ;; This is where we emulate the missing (define ...) expressions
;; for all the primitive procedures.(map list '((a b c) (1 2 3)))
    MAKE_CLOSURE(rax, SOB_NIL_ADDRESS, is_boolean)
    mov [fvar_tbl+8*0], rax
    MAKE_CLOSURE(rax, SOB_NIL_ADDRESS, is_float)
    mov [fvar_tbl+8*1], rax
    MAKE_CLOSURE(rax, SOB_NIL_ADDRESS, is_integer)
    mov [fvar_tbl+8*2], rax
    MAKE_CLOSURE(rax, SOB_NIL_ADDRESS, is_pair)
    mov [fvar_tbl+8*3], rax
    MAKE_CLOSURE(rax, SOB_NIL_ADDRESS, is_null)
    mov [fvar_tbl+8*4], rax
    MAKE_CLOSURE(rax, SOB_NIL_ADDRESS, is_char)
    mov [fvar_tbl+8*5], rax
    MAKE_CLOSURE(rax, SOB_NIL_ADDRESS, is_string)
    mov [fvar_tbl+8*6], rax
    MAKE_CLOSURE(rax, SOB_NIL_ADDRESS, is_procedure)
    mov [fvar_tbl+8*7], rax
    MAKE_CLOSURE(rax, SOB_NIL_ADDRESS, is_symbol)
    mov [fvar_tbl+8*8], rax
    MAKE_CLOSURE(rax, SOB_NIL_ADDRESS, string_length)
    mov [fvar_tbl+8*9], rax
    MAKE_CLOSURE(rax, SOB_NIL_ADDRESS, string_ref)
    mov [fvar_tbl+8*10], rax
    MAKE_CLOSURE(rax, SOB_NIL_ADDRESS, string_set)
    mov [fvar_tbl+8*11], rax
    MAKE_CLOSURE(rax, SOB_NIL_ADDRESS, make_string)
    mov [fvar_tbl+8*12], rax
    MAKE_CLOSURE(rax, SOB_NIL_ADDRESS, symbol_to_string)
    mov [fvar_tbl+8*13], rax
    MAKE_CLOSURE(rax, SOB_NIL_ADDRESS, char_to_integer)
    mov [fvar_tbl+8*14], rax
    MAKE_CLOSURE(rax, SOB_NIL_ADDRESS, integer_to_char)
    mov [fvar_tbl+8*15], rax
    MAKE_CLOSURE(rax, SOB_NIL_ADDRESS, is_eq)
    mov [fvar_tbl+8*16], rax
    MAKE_CLOSURE(rax, SOB_NIL_ADDRESS, bin_add)
    mov [fvar_tbl+8*17], rax
    MAKE_CLOSURE(rax, SOB_NIL_ADDRESS, bin_mul)
    mov [fvar_tbl+8*18], rax
    MAKE_CLOSURE(rax, SOB_NIL_ADDRESS, bin_sub)
    mov [fvar_tbl+8*19], rax
    MAKE_CLOSURE(rax, SOB_NIL_ADDRESS, bin_div)
    mov [fvar_tbl+8*20], rax
    MAKE_CLOSURE(rax, SOB_NIL_ADDRESS, bin_lt)
    mov [fvar_tbl+8*21], rax
    MAKE_CLOSURE(rax, SOB_NIL_ADDRESS, bin_equ)
    mov [fvar_tbl+8*22], rax
    MAKE_CLOSURE(rax, SOB_NIL_ADDRESS, car)
    mov [fvar_tbl+8*23], rax
    MAKE_CLOSURE(rax, SOB_NIL_ADDRESS, cdr)
    mov [fvar_tbl+8*24], rax
    MAKE_CLOSURE(rax, SOB_NIL_ADDRESS, cons_make)
    mov [fvar_tbl+8*25], rax
    MAKE_CLOSURE(rax, SOB_NIL_ADDRESS, set_car)
    mov [fvar_tbl+8*26], rax
    MAKE_CLOSURE(rax, SOB_NIL_ADDRESS, set_cdr)
    mov [fvar_tbl+8*27], rax
    MAKE_CLOSURE(rax, SOB_NIL_ADDRESS, apply)
    mov [fvar_tbl+8*28], rax

user_code_fragment:

;;; The code you compiled will be catenated here.
;;; It will be executed immediately after the closures for 
;;; the primitive procedures are set up.

MAKE_CLOSURE(rax, SOB_NIL_ADDRESS, Lcode_366831641)
jmp Lcont_366831641
Lcode_366831641:
push rbp
mov rbp, rsp

push SOB_NIL_ADDRESS

mov qword rax, [rbp + 32]

push rax

push 1

mov rsi, [rbp + 8 * 3]			;; (*rsi holds the number of parametres on the stack*)
inc rsi
lea rsi, [rsi * 8]
MALLOC rdx, rsi			;; (*now rdx points to the allocated memory for the new vector*)
mov rcx, [rbp + 8 * 3]
mov rdi, 0			;;(*rdi will be used to point to the next address in the vector*)

mov r9, 4
;; (*start of loop to copy parameters to the new allocated vector*)
copy_params_loop_641907500:
cmp rdi, rcx
je after_params_copy_641907500
mov rsi, [rbp + 8 * r9]			;;(*now rsi points to the next parameter on the stack*)
mov [rdx + 8*rdi], rsi			;;(*copying the parameter to the new allocated vector*)
inc rdi
inc r9
jmp copy_params_loop_641907500
;; (*now rdx points to the new vector to be added to ext_env*)
;; (*mov 0 to all neccessary registers*)
after_params_copy_641907500:
mov qword [rdx + 8*rdi], SOB_NIL_ADDRESS
mov rcx, 0
mov rdi, 0
mov rsi, 0
;; (*now we need to create ext_env by copying env and adding the new vector*)
MALLOC rbx, 16			;;(*rbx points to a new allocated space for ext_env*)
mov [rbx], rdx			;;(*copying the new vector to ext_env[0]*)
mov rsi, [rbp + 8 * 2]			;;(*rsi points to current env*)
mov rcx, 1			;;(*rcx is the loop counter*)
mov r9, 0			;;(*r9 will be used to point to the next vector in current env to be copied*)
mov rdi, 1			;;(*rdi will be used to point to the next address in ext_env*)
mov r8, 0
;; (*start of loop for copying env[i] to ext_env[i+1]*)
copy_env_loop_641907500:
cmp r9, rcx
je after_env_copy_641907500
mov r8, [rsi + 8 * r9]			;;(*r8 points to the next vector int current env to be copied*) 
mov [rbx + 8 * rdi], r8			;;(*copying the pointer to the vector from env to ext_env*)
inc r9
inc rdi
jmp copy_env_loop_641907500
after_env_copy_641907500:

MAKE_CLOSURE(rax, rbx, Lcode_641907500)
jmp Lcont_641907500
Lcode_641907500:
push rbp
mov r14, rbp
mov rbp, rsp
mov rdi, 0
mov rsi, qword [rbp + 8*3]
cmp qword rdi, rsi
jb vector_size_is_total_num_of_params_641907500
mov rsi, 0
mov rsi, 0
jmp create_vector_641907500
vector_size_is_total_num_of_params_641907500:
mov rsi, [rbp + 8*3]
create_vector_641907500:
lea rsi, [rsi*8]
mov r9, 0
mov rbx, 0
mov rdx, 0
MALLOC r9, rsi
mov rsi, 0
mov rsi, 0
mov rcx, 0
copy_non_opt_params_list_for_opt_641907500:
cmp rcx, rsi
je end_copy_non_opt_params_list_for_opt_641907500
mov rbx, qword PVAR(rcx)
mov qword [r9 + 8 * rcx], rbx
inc rcx
jmp copy_non_opt_params_list_for_opt_641907500
end_copy_non_opt_params_list_for_opt_641907500:
mov rsi, [rbp + 8*3]
cmp rsi, 0
je enlarge_stack_641907500
shrink_stack_641907500:
mov rdi, 0
dec rsi
mov r12, 0
mov r11, 0
mov r10, 0
mov r11, PVAR(rsi)
dec rsi
MAKE_PAIR(r12, r11, SOB_NIL_ADDRESS)
dec rdi
create_opt_params_list_641907500:
cmp rdi, rsi
je pop_and_adjust_stack_shrink_stack_641907500
mov r11, qword PVAR(rsi)
mov r10, r12
MAKE_PAIR(r12, r11, r10)
dec rsi
jmp create_opt_params_list_641907500
pop_and_adjust_stack_shrink_stack_641907500:
mov rsi, 0
mov rdi, 0
mov rcx,0
mov rbx, 0
mov rdi, [rbp + 8]
mov rcx, [rbp + 8*2]
mov rsi, [rbp + 8*3]
add rsp, 32
mov rbx, 0
lea rbx, [rsi*8]
add rsp, rbx
push qword r12
mov r12, 0
mov r12, 0
dec r12
mov rbx, 0
shrink_push_non_optional_params_loop_641907500:
cmp rbx, r12
jbe end_shrink_push_non_optional_params_loop_641907500
push qword [r9 + 8*r12]
dec r12
jmp shrink_push_non_optional_params_loop_641907500
end_shrink_push_non_optional_params_loop_641907500:
mov r15, 0
dec r15
cmp r15, r12
je dont_push_641907500
push qword [r9 + 8*r12]
dont_push_641907500:
mov rsi, 0
mov rsi, 0
inc rsi
push rsi
push rcx
push rdi
jmp body_of_opt_641907500
enlarge_stack_641907500:
mov rsi, 0
mov rdi, 0
mov rcx,0
mov rbx, 0
mov rdx, 0
mov rdx, qword [rbp + 8*3]
mov rdi, [rbp + 8]
mov rcx, [rbp + 8*2]
mov rsi, [rbp + 8*3]
add rsp, 32
lea rbx, [rsi*8]
add rsp, rbx
push SOB_NIL_ADDRESS
mov r10, 0
mov r11, 0
mov r10, rsi
dec r10
mov rbx, 0
enlarge_push_non_optional_params_loop_641907500:
cmp rbx, r10
jb end_enlarge_push_non_optional_params_loop_641907500
push qword [r9 + 8*r10]
dec r10
jmp enlarge_push_non_optional_params_loop_641907500
end_enlarge_push_non_optional_params_loop_641907500:
mov rsi, rdx
inc rsi
push rsi
push rcx
push rdi
body_of_opt_641907500:
mov rbp, r14
push rbp
mov rbp, rsp
mov qword rax, [rbp + 32]
my_stop:
mov rbx, [rsp + 8]

leave
ret
Lcont_641907500:


push qword [rax + 1]			;;(*pushing env on the stack*)
call [rax + 9]
add rsp, 8			;;(*popping the environment pointer*)
pop rbx			;;(*popping and saving the argument counter in rbx*)
shl rbx, 3			;;(*now rbx holds the sum of sizes of all the arguments to pop*)
add rsp, rbx			;;(*popping all the arguments*)
add rsp, 8
after_applic_332180439:

leave
ret
Lcont_366831641:


mov [fvar_tbl + 8*29], rax
mov rax, SOB_VOID_ADDRESS
	call write_sob_if_not_void


push SOB_NIL_ADDRESS

mov rax, const_tbl+6

push rax

push 1
mov rax, qword [fvar_tbl + 8*29]

push qword [rax + 1]			;;(*pushing env on the stack*)
call [rax + 9]
add rsp, 8			;;(*popping the environment pointer*)
pop rbx			;;(*popping and saving the argument counter in rbx*)
shl rbx, 3			;;(*now rbx holds the sum of sizes of all the arguments to pop*)
add rsp, rbx			;;(*popping all the arguments*)
add rsp, 8
after_applic_781944104:

	call write_sob_if_not_void

	mov rax, 0
	add rsp, 4*8
	pop rbp
	ret

car:
    push rbp
    mov rbp, rsp
    mov rsi, PVAR(0)    ; now rsi points to the possible pair
    CAR rax, rsi   ; now rax points to the car of the pair
    leave
    ret

cdr:
    push rbp
    mov rbp, rsp
    mov rsi, PVAR(0)    ; now rsi points to the possible pair
    CDR rax, rsi    ; now rax points to the cdr of the pair
    leave
    ret
cons_make:
    push rbp
    mov rbp, rsp
    mov rsi, PVAR(0)    ; now rsi points to the possible pair
    mov rdi, PVAR(1)
    MAKE_PAIR(rax, rsi ,rdi)
    leave
    ret
set_car:
    push rbp
    mov rbp, rsp
    mov rsi, PVAR(0)    ; now rsi points to the possible pair
    mov rdi, PVAR(1)    ; now rsi points to the possible pair
    mov qword [rsi+TYPE_SIZE],rdi
    leave 
    ret

set_cdr:
    push rbp
    mov rbp, rsp
    mov rsi, PVAR(0)    ; now rsi points to the possible pair
    mov rdi, PVAR(1)    ; now rsi points to the possible pair
    mov qword [rsi+TYPE_SIZE+WORD_SIZE],rdi
    leave 
    ret

apply:
    push rbp
    mov rbp, rsp
    mov rcx, qword [rbp + 8 * 3]   ; rcx holds the current args count
    mov r11, 0          ; cleaning r11 - r11 will hold the list length
    mov rsi, rcx                   ; rsi will hold at the end of the first loop the new argument count
    mov qword rbx, PVAR(0)         ; rbx points to the procedure to be applied
    dec rcx
    mov rdx, PVAR(rcx)             ; rdx holds the last parameter of apply which is a list
    dec rsi                         ; decrementing because we don't want to include the procedure argument
    dec rsi                         ; decrementing again because we don't want to include the list argument
    calculate_new_args_count_apply:     ; iterating over the list argument
       cmp rdx, SOB_NIL_ADDRESS
       je end_calculate_new_args_count_apply
       inc rsi                     ; incrementing the new number of argumnets
       inc r11                      ; incrementing the list length
       CDR rdx, rdx                 ; advancing to the next member of the list argument
       jmp calculate_new_args_count_apply
    end_calculate_new_args_count_apply:
    ; now rsi holds the new args count
    mov r9, 0
    mov r10, 0
    mov rcx, qword [rbp + 8 * 3]   ; rcx holds the current args count
    dec rcx                         ; rcx will be our loop counter
    dec rcx                         ; decrementing again because we don't want to include the procedure and the list argument
    lea r10, [rsi*8]        ; r10 holds the size of memory that is needed to save all the non list arguments
    MALLOC r9, r10          ; r9 points to the memory to save all the non list arguments
    mov r10, 1
    mov rdi, 0
    pop_and_save_all_non_list_arguments:
        cmp r10, rcx
        jg save_all_list_members
        mov rdi, PVAR(r10)      ; rdi holds the next argument to be saved
        mov qword [r9 + 8*r10], rdi ; saving the next argument in the new arguments vector
        inc r10
        jmp pop_and_save_all_non_list_arguments
    ; we saved all the non-list argumnets
    ; now we need to save all the members of the list as separate arguments
    ; r10 still points to the next address of the allocated memory to insert the next argument
    ; r9 still points to the vector of the new arguments 
    save_all_list_members:
        mov rcx, 0
        mov rcx, qword [rbp + 8 * 3]   ; rcx holds the current args count
        dec rcx
        mov rdx, 0
        mov r11, 0                  ; r11 will be used to save the next member of the list argument
        mov rdx, PVAR(rcx)          ; now rdx point to the list argument of apply
        save_all_list_members_loop:
            cmp rdx, SOB_NIL_ADDRESS
            je end_save_all_list_members
            CAR r11, rdx            ; next member in the list is in r11
            mov qword [r9 + r10*8], r11     ; saving the member in the new arguments vector
            inc r10
            CDR rdx, rdx                ; advancing to the next member of the list
            jmp save_all_list_members_loop
    end_save_all_list_members:
    ; first we need to clear the stack
    clear_stack:
        mov r8, 0
        mov r10, 0
        mov r11, 0
        mov r12, 0
        mov r8, qword [rbp + 8]                ; r8 holds the old ret address
        mov r10, qword [rbp + 8 * 2]            ; r10 points to the current env
        mov r11, qword [rbp + 8 * 3]       ; r11 holds the old args count
        add rsp, 32                         ; poping old rbp, old ret address, curr env and old args count
        lea r12, [r11 * 8]                  ; size of all the arguments is saved in r12
        add rsp, r12                        ; popping all the arguments
    ; now we need to push the new arguments on the stack
    ; push SOB_NIL_ADDRESS    ; pushing magic argument
    push_new_arguments:
    ; r9 points to a vector with all the arguments
    ; rsi is the number of arguments
        mov r12, 0
        mov r12, rsi         ; r12 holds the new number of arguments
        ; dec r12
        push_new_arguments_loop:        ; pushing all the new arguments from last to first
            cmp r12, 0
            je end_push_new_arguments
            push qword [r9 + 8*r12]
            dec r12
            jmp push_new_arguments_loop
    end_push_new_arguments:
    ; now we need to push the new args_count, the old env and the old ret address
    ; rbx still points to the procedure argument of apply
    push rsi        ; pushing new args count
    push qword [rbx + 1]        ; pushing the closure env on the stack
    push r8         ; pushing the old ret address
    jmp [rbx + 9]        ; calling the procedure argument
    ;leave 
    ;ret

is_boolean:
    push rbp
    mov rbp, rsp

    mov rsi, PVAR(0)
    mov sil, byte [rsi]

    cmp sil, T_BOOL
    jne .wrong_type
    mov rax, SOB_TRUE_ADDRESS
    jmp .return

.wrong_type:
    mov rax, SOB_FALSE_ADDRESS
.return:
    leave
    ret

is_float:
    push rbp
    mov rbp, rsp

    mov rsi, PVAR(0)
    mov sil, byte [rsi]

    cmp sil, T_FLOAT
    jne .wrong_type
    mov rax, SOB_TRUE_ADDRESS
    jmp .return

.wrong_type:
    mov rax, SOB_FALSE_ADDRESS
.return:
    leave
    ret

is_integer:
    push rbp
    mov rbp, rsp

    mov rsi, PVAR(0)
    mov sil, byte [rsi]

    cmp sil, T_INTEGER
    jne .wrong_type
    mov rax, SOB_TRUE_ADDRESS
    jmp .return

.wrong_type:
    mov rax, SOB_FALSE_ADDRESS
.return:
    leave
    ret

is_pair:
    push rbp
    mov rbp, rsp

    mov rsi, PVAR(0)
    mov sil, byte [rsi]

    cmp sil, T_PAIR
    jne .wrong_type
    mov rax, SOB_TRUE_ADDRESS
    jmp .return

.wrong_type:
    mov rax, SOB_FALSE_ADDRESS
.return:
    leave
    ret

is_null:
    push rbp
    mov rbp, rsp

    mov rsi, PVAR(0)
    mov sil, byte [rsi]

    cmp sil, T_NIL
    jne .wrong_type
    mov rax, SOB_TRUE_ADDRESS
    jmp .return

.wrong_type:
    mov rax, SOB_FALSE_ADDRESS
.return:
    leave
    ret

is_char:
    push rbp
    mov rbp, rsp

    mov rsi, PVAR(0)
    mov sil, byte [rsi]

    cmp sil, T_CHAR
    jne .wrong_type
    mov rax, SOB_TRUE_ADDRESS
    jmp .return

.wrong_type:
    mov rax, SOB_FALSE_ADDRESS
.return:
    leave
    ret

is_string:
    push rbp
    mov rbp, rsp

    mov rsi, PVAR(0)
    mov sil, byte [rsi]

    cmp sil, T_STRING
    jne .wrong_type
    mov rax, SOB_TRUE_ADDRESS
    jmp .return

.wrong_type:
    mov rax, SOB_FALSE_ADDRESS
.return:
    leave
    ret

is_procedure:
    push rbp
    mov rbp, rsp

    mov rsi, PVAR(0)
    mov sil, byte [rsi]

    cmp sil, T_CLOSURE
    jne .wrong_type
    mov rax, SOB_TRUE_ADDRESS
    jmp .return

.wrong_type:
    mov rax, SOB_FALSE_ADDRESS
.return:
    leave
    ret

is_symbol:
    push rbp
    mov rbp, rsp

    mov rsi, PVAR(0)
    mov sil, byte [rsi]

    cmp sil, T_SYMBOL
    jne .wrong_type
    mov rax, SOB_TRUE_ADDRESS
    jmp .return

.wrong_type:
    mov rax, SOB_FALSE_ADDRESS
.return:
    leave
    ret

string_length:
    push rbp
    mov rbp, rsp

    mov rsi, PVAR(0)
    STRING_LENGTH rsi, rsi
    MAKE_INT(rax, rsi)

    leave
    ret

string_ref:
    push rbp
    mov rbp, rsp

    mov rsi, PVAR(0) 
    STRING_ELEMENTS rsi, rsi
    mov rdi, PVAR(1)
    INT_VAL rdi, rdi
    shl rdi, 0
    add rsi, rdi

    mov sil, byte [rsi]
    MAKE_CHAR(rax, sil)

    leave
    ret

string_set:
    push rbp
    mov rbp, rsp

    mov rsi, PVAR(0) 
    STRING_ELEMENTS rsi, rsi
    mov rdi, PVAR(1)
    INT_VAL rdi, rdi
    shl rdi, 0
    add rsi, rdi

    mov rax, PVAR(2)
    CHAR_VAL rax, rax
    mov byte [rsi], al
    mov rax, SOB_VOID_ADDRESS

    leave
    ret

make_string:
    push rbp
    mov rbp, rsp

    
    mov rsi, PVAR(0)
    INT_VAL rsi, rsi
    mov rdi, PVAR(1)
    CHAR_VAL rdi, rdi
    and rdi, 255

    MAKE_STRING rax, rsi, dil

    leave
    ret

symbol_to_string:
    push rbp
    mov rbp, rsp

    
    mov rsi, PVAR(0)
    SYMBOL_VAL rsi, rsi
    
    STRING_LENGTH rcx, rsi
    STRING_ELEMENTS rdi, rsi

    push rcx
    push rdi

    mov dil, byte [rdi]
    MAKE_CHAR(rax, dil)
    push rax
    MAKE_INT(rax, rcx)
    push rax
    push 2
    push SOB_NIL_ADDRESS
    call make_string
    add rsp, 4*8

    STRING_ELEMENTS rsi, rax

    pop rdi
    pop rcx

    cmp rcx, 0
    je .end
	
.loop:
    lea r8, [rdi+rcx]
    lea r9, [rsi+rcx]

    mov bl, byte [r8]
    mov byte [r9], bl
    
    loop .loop
.end:

    leave
    ret

char_to_integer:
    push rbp
    mov rbp, rsp

    
    mov rsi, PVAR(0)
    CHAR_VAL rsi, rsi
    and rsi, 255
    MAKE_INT(rax, rsi)

    leave
    ret

integer_to_char:
    push rbp
    mov rbp, rsp

    
    mov rsi, PVAR(0)
    INT_VAL rsi, rsi
    and rsi, 255
    MAKE_CHAR(rax, sil)

    leave
    ret

is_eq:
    push rbp
    mov rbp, rsp

    
    mov rsi, PVAR(0)
    mov rdi, PVAR(1)
    cmp rsi, rdi
    je .true
    mov rax, SOB_FALSE_ADDRESS
    jmp .return

.true:
    mov rax, SOB_TRUE_ADDRESS

.return:
    leave
    ret

bin_add:
    push rbp
    mov rbp, rsp

    mov r8, 0

    mov rsi, PVAR(0)
    push rsi
    push 1
    push SOB_NIL_ADDRESS
    call is_float
    add rsp, 3*WORD_SIZE 


    cmp rax, SOB_TRUE_ADDRESS
    je .test_next
    or r8, 1

.test_next:

    mov rsi, PVAR(1)
    push rsi
    push 1
    push SOB_NIL_ADDRESS
    call is_float
    add rsp, 3*WORD_SIZE 


    cmp rax, SOB_TRUE_ADDRESS
    je .load_numbers
    or r8, 2

.load_numbers:
    push r8

    shr r8, 1
    jc .first_arg_int
    mov rsi, PVAR(0)
    FLOAT_VAL rsi, rsi 
    movq xmm0, rsi
    jmp .load_next_float

.first_arg_int:
    mov rsi, PVAR(0)
    INT_VAL rsi, rsi
    cvtsi2sd xmm0, rsi

.load_next_float:
    shr r8, 1
    jc .second_arg_int
    mov rsi, PVAR(1)
    FLOAT_VAL rsi, rsi
    movq xmm1, rsi
    jmp .perform_float_op

.second_arg_int:
    mov rsi, PVAR(1)
    INT_VAL rsi, rsi
    cvtsi2sd xmm1, rsi

.perform_float_op:
    addsd xmm0, xmm1

    pop r8
    cmp r8, 3
    jne .return_float

    cvttsd2si rsi, xmm0
    MAKE_INT(rax, rsi)
    jmp .return

.return_float:
    movq rsi, xmm0
    MAKE_FLOAT(rax, rsi)

.return:

    leave
    ret

bin_mul:
    push rbp
    mov rbp, rsp

    mov r8, 0

    mov rsi, PVAR(0)
    push rsi
    push 1
    push SOB_NIL_ADDRESS
    call is_float
    add rsp, 3*WORD_SIZE 


    cmp rax, SOB_TRUE_ADDRESS
    je .test_next
    or r8, 1

.test_next:

    mov rsi, PVAR(1)
    push rsi
    push 1
    push SOB_NIL_ADDRESS
    call is_float
    add rsp, 3*WORD_SIZE 


    cmp rax, SOB_TRUE_ADDRESS
    je .load_numbers
    or r8, 2

.load_numbers:
    push r8

    shr r8, 1
    jc .first_arg_int
    mov rsi, PVAR(0)
    FLOAT_VAL rsi, rsi 
    movq xmm0, rsi
    jmp .load_next_float

.first_arg_int:
    mov rsi, PVAR(0)
    INT_VAL rsi, rsi
    cvtsi2sd xmm0, rsi

.load_next_float:
    shr r8, 1
    jc .second_arg_int
    mov rsi, PVAR(1)
    FLOAT_VAL rsi, rsi
    movq xmm1, rsi
    jmp .perform_float_op

.second_arg_int:
    mov rsi, PVAR(1)
    INT_VAL rsi, rsi
    cvtsi2sd xmm1, rsi

.perform_float_op:
    mulsd xmm0, xmm1

    pop r8
    cmp r8, 3
    jne .return_float

    cvttsd2si rsi, xmm0
    MAKE_INT(rax, rsi)
    jmp .return

.return_float:
    movq rsi, xmm0
    MAKE_FLOAT(rax, rsi)

.return:

    leave
    ret

bin_sub:
    push rbp
    mov rbp, rsp

    mov r8, 0

    mov rsi, PVAR(0)
    push rsi
    push 1
    push SOB_NIL_ADDRESS
    call is_float
    add rsp, 3*WORD_SIZE 


    cmp rax, SOB_TRUE_ADDRESS
    je .test_next
    or r8, 1

.test_next:

    mov rsi, PVAR(1)
    push rsi
    push 1
    push SOB_NIL_ADDRESS
    call is_float
    add rsp, 3*WORD_SIZE 


    cmp rax, SOB_TRUE_ADDRESS
    je .load_numbers
    or r8, 2

.load_numbers:
    push r8

    shr r8, 1
    jc .first_arg_int
    mov rsi, PVAR(0)
    FLOAT_VAL rsi, rsi 
    movq xmm0, rsi
    jmp .load_next_float

.first_arg_int:
    mov rsi, PVAR(0)
    INT_VAL rsi, rsi
    cvtsi2sd xmm0, rsi

.load_next_float:
    shr r8, 1
    jc .second_arg_int
    mov rsi, PVAR(1)
    FLOAT_VAL rsi, rsi
    movq xmm1, rsi
    jmp .perform_float_op

.second_arg_int:
    mov rsi, PVAR(1)
    INT_VAL rsi, rsi
    cvtsi2sd xmm1, rsi

.perform_float_op:
    subsd xmm0, xmm1

    pop r8
    cmp r8, 3
    jne .return_float

    cvttsd2si rsi, xmm0
    MAKE_INT(rax, rsi)
    jmp .return

.return_float:
    movq rsi, xmm0
    MAKE_FLOAT(rax, rsi)

.return:

    leave
    ret

bin_div:
    push rbp
    mov rbp, rsp

    mov r8, 0

    mov rsi, PVAR(0)
    push rsi
    push 1
    push SOB_NIL_ADDRESS
    call is_float
    add rsp, 3*WORD_SIZE 


    cmp rax, SOB_TRUE_ADDRESS
    je .test_next
    or r8, 1

.test_next:

    mov rsi, PVAR(1)
    push rsi
    push 1
    push SOB_NIL_ADDRESS
    call is_float
    add rsp, 3*WORD_SIZE 


    cmp rax, SOB_TRUE_ADDRESS
    je .load_numbers
    or r8, 2

.load_numbers:
    push r8

    shr r8, 1
    jc .first_arg_int
    mov rsi, PVAR(0)
    FLOAT_VAL rsi, rsi 
    movq xmm0, rsi
    jmp .load_next_float

.first_arg_int:
    mov rsi, PVAR(0)
    INT_VAL rsi, rsi
    cvtsi2sd xmm0, rsi

.load_next_float:
    shr r8, 1
    jc .second_arg_int
    mov rsi, PVAR(1)
    FLOAT_VAL rsi, rsi
    movq xmm1, rsi
    jmp .perform_float_op

.second_arg_int:
    mov rsi, PVAR(1)
    INT_VAL rsi, rsi
    cvtsi2sd xmm1, rsi

.perform_float_op:
    divsd xmm0, xmm1

    pop r8
    cmp r8, 3
    jne .return_float

    cvttsd2si rsi, xmm0
    MAKE_INT(rax, rsi)
    jmp .return

.return_float:
    movq rsi, xmm0
    MAKE_FLOAT(rax, rsi)

.return:

    leave
    ret

bin_lt:
    push rbp
    mov rbp, rsp

    mov r8, 0

    mov rsi, PVAR(0)
    push rsi
    push 1
    push SOB_NIL_ADDRESS
    call is_float
    add rsp, 3*WORD_SIZE 


    cmp rax, SOB_TRUE_ADDRESS
    je .test_next
    or r8, 1

.test_next:

    mov rsi, PVAR(1)
    push rsi
    push 1
    push SOB_NIL_ADDRESS
    call is_float
    add rsp, 3*WORD_SIZE 


    cmp rax, SOB_TRUE_ADDRESS
    je .load_numbers
    or r8, 2

.load_numbers:
    push r8

    shr r8, 1
    jc .first_arg_int
    mov rsi, PVAR(0)
    FLOAT_VAL rsi, rsi 
    movq xmm0, rsi
    jmp .load_next_float

.first_arg_int:
    mov rsi, PVAR(0)
    INT_VAL rsi, rsi
    cvtsi2sd xmm0, rsi

.load_next_float:
    shr r8, 1
    jc .second_arg_int
    mov rsi, PVAR(1)
    FLOAT_VAL rsi, rsi
    movq xmm1, rsi
    jmp .perform_float_op

.second_arg_int:
    mov rsi, PVAR(1)
    INT_VAL rsi, rsi
    cvtsi2sd xmm1, rsi

.perform_float_op:
    cmpltsd xmm0, xmm1

    pop r8
    cmp r8, 3
    jne .return_float

    cvttsd2si rsi, xmm0
    MAKE_INT(rax, rsi)
    jmp .return

.return_float:
    movq rsi, xmm0
    MAKE_FLOAT(rax, rsi)

.return:

    INT_VAL rsi, rax
    cmp rsi, 0
    je .return_false
    mov rax, SOB_TRUE_ADDRESS
    jmp .final_return

.return_false:
    mov rax, SOB_FALSE_ADDRESS

.final_return:


    leave
    ret

bin_equ:
    push rbp
    mov rbp, rsp

    mov r8, 0

    mov rsi, PVAR(0)
    push rsi
    push 1
    push SOB_NIL_ADDRESS
    call is_float
    add rsp, 3*WORD_SIZE 


    cmp rax, SOB_TRUE_ADDRESS
    je .test_next
    or r8, 1

.test_next:

    mov rsi, PVAR(1)
    push rsi
    push 1
    push SOB_NIL_ADDRESS
    call is_float
    add rsp, 3*WORD_SIZE 


    cmp rax, SOB_TRUE_ADDRESS
    je .load_numbers
    or r8, 2

.load_numbers:
    push r8

    shr r8, 1
    jc .first_arg_int
    mov rsi, PVAR(0)
    FLOAT_VAL rsi, rsi 
    movq xmm0, rsi
    jmp .load_next_float

.first_arg_int:
    mov rsi, PVAR(0)
    INT_VAL rsi, rsi
    cvtsi2sd xmm0, rsi

.load_next_float:
    shr r8, 1
    jc .second_arg_int
    mov rsi, PVAR(1)
    FLOAT_VAL rsi, rsi
    movq xmm1, rsi
    jmp .perform_float_op

.second_arg_int:
    mov rsi, PVAR(1)
    INT_VAL rsi, rsi
    cvtsi2sd xmm1, rsi

.perform_float_op:
    cmpeqsd xmm0, xmm1

    pop r8
    cmp r8, 3
    jne .return_float

    cvttsd2si rsi, xmm0
    MAKE_INT(rax, rsi)
    jmp .return

.return_float:
    movq rsi, xmm0
    MAKE_FLOAT(rax, rsi)

.return:

    INT_VAL rsi, rax
    cmp rsi, 0
    je .return_false
    mov rax, SOB_TRUE_ADDRESS
    jmp .final_return

.return_false:
    mov rax, SOB_FALSE_ADDRESS

.final_return:


    leave
    ret


